import{S,i as l}from"./assets/vendor-46aac873.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const o of n.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&i(o)}).observe(document,{childList:!0,subtree:!0});function s(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerpolicy&&(n.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?n.credentials="include":t.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(t){if(t.ep)return;t.ep=!0;const n=s(t);fetch(t.href,n)}})();const p=document.querySelector(".form"),d=document.querySelector(".gallery"),a=document.querySelector(".loader"),u=document.querySelector(".load-more-btn"),f=new S(".gallery a",{captionsData:"alt",captionDelay:250});let c=1,m="";p.addEventListener("submit",b);u.addEventListener("click",M);async function b(r){r.preventDefault();const e=r.currentTarget.elements.input.value;if(d.innerHTML="",a.classList.remove("is-hidden"),c=1,m=e,!e.trim()){l.warning({message:"Please, fill in the search field",position:"topLeft",timeout:3e3}),a.classList.add("is-hidden"),L();return}let s;try{s=await g(e),s.hits.length===0?l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:5e3}):(d.innerHTML=y(s.hits),f.refresh(),h(15,s))}catch(i){v(i)}finally{a.classList.add("is-hidden"),s&&h(15,s.totalHits)}p&&p.reset()}function g(r){const e="https://pixabay.com/api/",i=new URLSearchParams({key:"42027170-68cc294651d415255967a4fd3",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:c,per_page:15});return fetch(`${e}/?${i}`).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()})}function y(r){return r.map(({webformatURL:e,largeImageURL:s,tags:i,likes:t,views:n,comments:o,downloads:w})=>`<li class="gallery-item">
        <a class="gallery-link" href="${s}">
           <img class="gallery-image" src="${e}" alt="${i}" />
        </a>
        <div class="container-additional-info">
          <div class="container-descr-inner"><p class="description">Likes</p><span class="description-value">${t}</span></div>
          <div class="container-descr-inner"><p class="description">Views</p><span class="description-value">${n}</span></div>
          <div class="container-descr-inner"><p class="description">Comments</p><span class="description-value">${o}</span></div>
          <div class="container-descr-inner"><p class="description">Downloads</p><span class="description-value">${w}</span></div>
        </div>
      </li>`).join("")}function v(r){console.error(r),d.innerHTML="",l.error({message:"Sorry, there is a problem with the connection with the server.",position:"center",timeout:5e3})}function M(){c++,a.classList.remove("is-hidden"),L();const r=document.querySelector(".gallery-item").getBoundingClientRect().height;g(m).then(e=>{if(e.hits.length>0){const s=y(e.hits);d.insertAdjacentHTML("beforeend",s),f.refresh();const i=r*2;window.scrollBy({top:i,behavior:"smooth"})}h(e.hits.length,e.totalHits)}).catch(v).finally(()=>{a.classList.add("is-hidden")})}function L(){u.style.display="none"}function h(r,e){r>=15&&e&&c*15<e?u.style.display="block":(u.style.display="none",e&&c*15>=e&&$())}function $(){l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:5e3})}
//# sourceMappingURL=commonHelpers.js.map
