import{S as L,a as w,i as S}from"./assets/vendor-951421c8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))n(s);new MutationObserver(s=>{for(const o of s)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(s){const o={};return s.integrity&&(o.integrity=s.integrity),s.referrerpolicy&&(o.referrerPolicy=s.referrerpolicy),s.crossorigin==="use-credentials"?o.credentials="include":s.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(s){if(s.ep)return;s.ep=!0;const o=r(s);fetch(s.href,o)}})();const p=document.querySelector(".form"),l=document.querySelector(".gallery"),f=document.querySelector(".loader"),d=document.querySelector(".load-more-btn"),M=new L(".gallery a",{captionsData:"alt",captionDelay:250});let a=1;p.addEventListener("submit",b);d.addEventListener("click",x);let c=!1;function b(e){e.preventDefault();const t=e.currentTarget.elements.input.value;if(l.innerHTML="",a=1,h(),!t.trim()){u({title:"❕",theme:"light",message:"Please, fill in the search field",messageSize:"20px",messageColor:"#808080",backgroundColor:"#e7fc44",position:"topLeft",timeout:3e3});return}g(t)}async function g(e){try{const t=await k(e,a);t.hits.length===0?u({title:"❕",theme:"dark",message:"Sorry, there are no images matching your search query. Please try again!",messageSize:"16px",messageColor:"white",backgroundColor:"#EF4040",position:"topRight",timeout:5e3}):(l.innerHTML+=C(t.hits),M.refresh(),H(),h(),B(),t.hits.length<t.totalHits?E(t.totalHits,t.hits):(m(),y(),c=!0))}catch(t){q(t)}finally{f.classList.add("is-hidden")}}function E(e){e-a*15<=0&&(m(),c||(y(),c=!0))}async function k(e,t=1,r=15){const n="https://pixabay.com/api/",s="42027170-68cc294651d415255967a4fd3";try{const o=await w.get(n,{params:{key:s,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:r}});if(o.status!==200)throw new Error(o.status);return o.data}catch(o){throw new Error(o)}}function C(e){return e.map(({webformatURL:t,largeImageURL:r,tags:n,likes:s,views:o,comments:i,downloads:v})=>`<li class="gallery-item">
        <a class="gallery-link" href="${r}">
           <img class="gallery-image" src="${t}" alt="${n}" />
        </a>
        <div class="container-additional-info">
          <div class="container-descr-inner"><p class="description">Likes</p><span class="description-value">${s}</span></div>
          <div class="container-descr-inner"><p class="description">Views</p><span class="description-value">${o}</span></div>
          <div class="container-descr-inner"><p class="description">Comments</p><span class="description-value">${i}</span></div>
          <div class="container-descr-inner"><p class="description">Downloads</p><span class="description-value">${v}</span></div>
        </div>
      </li>`).join("")}function u(e){S.show(e)}function q(e){console.error(e),l.innerHTML="",u({title:"❕",theme:"dark",message:"Sorry, there is a problem with the connection to the server.",messageSize:"16px",messageColor:"white",backgroundColor:"#EF4040",position:"center",timeout:5e3})}function x(){a+=1;const e=p.elements.input.value;f.classList.remove("is-hidden"),m(),h(),g(e)}function H(){d.classList.remove("is-hidden")}function m(){d.classList.add("is-hidden")}function y(){const e=document.createElement("div");e.classList.add("end-message"),e.textContent="We're sorry, but you've reached the end of search results.",document.body.appendChild(e)}function h(){const e=document.querySelector(".end-message");e&&e.remove()}function B(){const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
