import{S as y,a as v,i as L}from"./assets/vendor-951421c8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))r(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function s(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerpolicy&&(n.referrerPolicy=o.referrerpolicy),o.crossorigin==="use-credentials"?n.credentials="include":o.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function r(o){if(o.ep)return;o.ep=!0;const n=s(o);fetch(o.href,n)}})();const u="path/to/icon.png",m=document.querySelector(".form"),c=document.querySelector(".gallery"),p=document.querySelector(".loader"),l=document.querySelector(".load-more-btn"),w=new y(".gallery a",{captionsData:"alt",captionDelay:250});let a=1;m.addEventListener("submit",S);l.addEventListener("click",C);function S(e){e.preventDefault();const t=e.currentTarget.elements.input.value;if(c.innerHTML="",a=1,!t.trim()){d({title:"❕",theme:"light",message:"Please, fill in the search field",messageSize:"20px",messageColor:"#808080",backgroundColor:"#e7fc44",position:"topLeft",timeout:3e3});return}h(t)}async function h(e){try{const t=await M(e,a);t.hits.length===0?d({iconUrl:u,theme:"dark",message:"Sorry, there are no images matching your search query. Please try again!",messageSize:"16px",messageColor:"white",backgroundColor:"#EF4040",position:"topRight",timeout:5e3}):(c.innerHTML+=E(t.hits),w.refresh(),q(),B(),H()),b(t.totalHits,t.hits)}catch(t){k(t)}finally{p.classList.add("is-hidden")}}function b(e,t){e-a*15<=0&&t.length===0&&(f(),x())}async function M(e,t=1,s=15){const r="https://pixabay.com/api/",o="42027170-68cc294651d415255967a4fd3";try{const n=await v.get(r,{params:{key:o,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:s}});if(n.status!==200)throw new Error(n.status);return n.data}catch(n){throw new Error(n)}}function E(e){return e.map(({webformatURL:t,largeImageURL:s,tags:r,likes:o,views:n,comments:i,downloads:g})=>`<li class="gallery-item">
        <a class="gallery-link" href="${s}">
           <img class="gallery-image" src="${t}" alt="${r}" />
        </a>
        <div class="container-additional-info">
          <div class="container-descr-inner"><p class="description">Likes</p><span class="description-value">${o}</span></div>
          <div class="container-descr-inner"><p class="description">Views</p><span class="description-value">${n}</span></div>
          <div class="container-descr-inner"><p class="description">Comments</p><span class="description-value">${i}</span></div>
          <div class="container-descr-inner"><p class="description">Downloads</p><span class="description-value">${g}</span></div>
        </div>
      </li>`).join("")}function d(e){L.show(e)}function k(e,t){console.error(e),c.innerHTML="",d({iconUrl:u,theme:"dark",message:"Sorry, there is a problem with the connection to the server.",messageSize:"16px",messageColor:"white",backgroundColor:"#EF4040",position:"center",timeout:5e3})}function C(){a+=1;const e=m.elements.input.value;p.classList.remove("is-hidden"),f(),h(e)}function q(){l.classList.remove("is-hidden")}function f(){l.classList.add("is-hidden")}function x(){const e=document.createElement("div");e.classList.add("end-message"),e.textContent="We're sorry, but you've reached the end of search results.",document.body.appendChild(e)}function B(){const e=document.querySelector(".end-message");e&&e.remove()}function H(){const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
